name: resumeapp
description: A Resume App


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Google Fonts
  google_fonts: ^3.0.1
  # State Management
  provider: ^6.0.4
  #App Responsiveness
  flutter_screenutil: ^5.6.0
  #Svg
  flutter_svg: ^1.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  generate: true

  uses-material-design: true


  assets:
    - assets/svg/
    - assets/png/

flutter_intl:
  enabled: false